spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tNe7NQiys65EiPubsBD
      secret-key: RCQASRdqHbieh8FnuQLxghoh5AOtfy
      oss:
        endpoint: oss-cn-shanghai.aliyuncs.com
        bucket: gulimall-irene

  application:
    name: gulimall-third-party

server:
  port: 30000
